
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx-dep
  labels:
    app: app-nginx
spec:
  selector:
    matchLabels:
      app: app-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
      - name: mynginx
        image: mynginx
        imagePullPolicy: Never
        ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
          - containerPort: 22
            name: ssh
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx-svc
  labels:
    app: app-nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  - port: 22
    targetPort: 22
    name: ssh
  selector:
    app: app-nginx
